# Generated by Django 3.1.4 on 2021-03-27 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='bootcamp',
            field=models.ImageField(null=True, upload_to='ecell_certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='eureka_jr',
            field=models.ImageField(null=True, upload_to='ecell_certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vsm',
            field=models.ImageField(null=True, upload_to='ecell_certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='workshop',
            field=models.ImageField(null=True, upload_to='ecell_certificate'),
        ),
    ]
