# Generated by Django 3.1.4 on 2021-03-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20210327_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='bootcamp',
            field=models.ImageField(blank=True, null=True, upload_to='ecell_certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='eureka_jr',
            field=models.ImageField(blank=True, null=True, upload_to='ecell_certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='vsm',
            field=models.ImageField(blank=True, null=True, upload_to='ecell_certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='workshop',
            field=models.ImageField(blank=True, null=True, upload_to='ecell_certificate'),
        ),
    ]
