# Generated by Django 3.1.4 on 2021-03-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20210327_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='eureka_jr',
            field=models.ImageField(blank=True, null=True, upload_to='ecell_certificate'),
        ),
    ]
