# Generated by Django 3.1.4 on 2021-03-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20210327_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='vsm',
        ),
    ]
